### ISSUE TITLE
Failed to fetch token info. Status code: 403

### ISSUE THREAD

**Issue by sadathmd** [1f1n/gmgnai-wrapper#3]
I am getting the following error while running the code.

Failed to fetch token info. Status code: 403
Response Text: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment.

A 403 status code indicates that the server understands your request but is refusing to authorize it. This typically suggests an issue with permissions or access control. What should be done to address the issue?

**Comment by tigermumu** [comment]
I write scraper code with python requests. it is got 200 and correct data at local PC windows system. but get 403 at VPS ubuntu system. I don`t know why...

**Comment by tigermumu** [comment]
from curl_cffi import requests
it should be using curl_cffi . solved

**Comment by 0dian** [comment]
![image](https://github.com/user-attachments/assets/e87e95d7-f453-45f9-9c3a-31bc453a1c58)
Please help me.

**Comment by 1f1n** [comment]
> ![image](https://private-user-images.githubusercontent.com/13231255/383507644-e87e95d7-f453-45f9-9c3a-31bc453a1c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDU0MzEsIm5iZiI6MTczMDkwNTEzMSwicGF0aCI6Ii8xMzIzMTI1NS8zODM1MDc2NDQtZTg3ZTk1ZDctZjQ1My00NWY5LTljM2EtMzFiYzQ1M2ExYzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE0NTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWQ3OTcxMDUzZWFkMjMyYjgyNWZlMzhlOGUwMzZjYjNjY2QzZmMwNjU2ZGMzYzEyYTQwM2QxZTQwYTBjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.42Ya0p-e3BrAMTRKYOOwFxlowpscBimIoWH08B0rMZM) Please help me.


Randomise your User Agent with different browsers and operating systems, then randomise your TLS fingerprint too.
